%% @brief: Display shots of the video sampled at a certain rate
%
%  @paramters:
%  imgDir - directory of frames extracted from video
%  shotFile - shot file generated by the software using color histogram
%  shotNumber - the shot to display


function displayShots(imgDir, shotFile, shotNum)

fid = fopen(shotFile);
shotData = textscan(fid, '%s%d%d', 'Headerlines', 2, 'Delimiter', ',');
fclose(fid);

imageNames = shotData{1};
isShotChange = shotData{2};
shotNumber = shotData{3};

imageNames = imageNames(shotNumber==shotNum);
sampleRate = 16;

sampleDiff = round(numel(imageNames)/sampleRate);
finalFrame = min(numel(imageNames), sampleDiff*(sampleRate-1) + 1);

%% Show in a 4X4 plot 
% resize image to 200 X (...)
ctr = 1;
for i = 1:sampleDiff:finalFrame
  im = imread([imgDir '/' imageNames{i}]);
  [m,n] = size(im);
  im = imresize(im, round(200.0/m));
  subplot(4,4,ctr);
  imshow(im);
  ctr = ctr + 1;
end
